INSERT INTO CAR (ID, COLOR, MAKE, MODEL, YEAR, CREATED_DATE, LAST_MODIFIED_DATE) VALUES (1, 1, 'Audi', 'A5', 2018, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CAR (ID, COLOR, MAKE, MODEL, YEAR, CREATED_DATE, LAST_MODIFIED_DATE) VALUES (2, 3, 'Audi', 'A4', 2014, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CAR (ID, COLOR, MAKE, MODEL, YEAR, CREATED_DATE, LAST_MODIFIED_DATE) VALUES (3, 4, 'Infiniti', 'G35', 2008, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
